### PR TITLE
fix: update edge_auto_launcher tasks

### PR DESCRIPTION
**Pull request by tokuda99**
- Added a task to check if the GitHub API return is valid
- Added a task to ensure driver_deb_download_url is defined
- Added tasks to extract and fix the driver tar.gz file
- Added a task to run the installation script
- Removed the task to install the driver from deb file
- Removed the task to install the SDK from deb file
- Updated the task to setup camera driver and SDK
- Added an ansible task to download install missing object detection model
- Updates the object detection launcher to use the models downloaded in the previous step.

Verified using the following command, after a successful installation with ansible and a restart to allow the camera driver to load.
`ros2 launch edge_auto_jetson_launch edge_auto_jetson.launch.xml`

### CODE REVIEW

**Comment by manato** [comment]
@tokuda99 @amc-nu 
Thank you very much for handling this issue, and we are sorry to make things complicated.
Because `tar.gz` file this PR refers to is dedicated to the CTI Anvil platform, I guess it probably does not work on RQX-58G. Hence, could you please use [v1.4.3](https://github.com/tier4/tier4_automotive_hdr_camera/releases/tag/v1.4.3) camera driver for RQX-58G platform? This is the latest version that RQX-58G is supported.

**Comment by amc-nu** [comment]
@manato @drwnz 
The new Autoware TensorRT YoloX node uses nested namespaces (`autoware::tensorrt_yolox`), which is incompatible with the CUDA compiler in the ROSCUBE. The following change in the code is required.

```diff
diff --git a/perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/tensorrt_yolox_node.hpp b/perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/tensorrt_yolox_node.hpp
index 7f622b2dc8..cf7b051b9e 100644
--- a/perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/tensorrt_yolox_node.hpp
+++ b/perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/tensorrt_yolox_node.hpp
@@ -42,8 +42,8 @@
 #include <string>
 #include <vector>
 
-namespace autoware::tensorrt_yolox
-{
+namespace autoware {
+namespace tensorrt_yolox {
 // cspell: ignore Semseg
 using LabelMap = std::map<int, std::string>;
 using Label = tier4_perception_msgs::msg::Semantic;
@@ -110,6 +110,6 @@ private:
   std::unique_ptr<autoware::universe_utils::DebugPublisher> debug_publisher_;
 };
 
-}  // namespace autoware::tensorrt_yolox
-
+}  // namespace tensorrt_yolox
+}  // namespace autoware
 #endif  // AUTOWARE__TENSORRT_YOLOX__TENSORRT_YOLOX_NODE_HPP_
diff --git a/perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp b/perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp
index f3c7b2552e..ed57c598be 100644
--- a/perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp
+++ b/perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp
@@ -24,8 +24,8 @@
 #include <utility>
 #include <vector>
 
-namespace autoware::tensorrt_yolox
-{
+namespace autoware {
+namespace tensorrt_yolox {
 TrtYoloXNode::TrtYoloXNode(const rclcpp::NodeOptions & node_options)
 : Node("tensorrt_yolox", node_options)
 {
@@ -281,7 +281,8 @@ void TrtYoloXNode::overlapSegmentByRoi(
                        .rowRange(roi_y_offset, roi_y_offset + roi_height));
 }
 
-}  // namespace autoware::tensorrt_yolox
+}  // namespace tensorrt_yolox
+}  // namespace autoware
 
 #include "rclcpp_components/register_node_macro.hpp"
 RCLCPP_COMPONENTS_REGISTER_NODE(autoware::tensorrt_yolox::TrtYoloXNode)
```

**Review by manato — APPROVED** [review]
@amc-nu @tokuda99 @urasakikeisuke 
I appreciate your support! Similar to https://github.com/tier4/edge-auto/pull/19, I approve this PR as a first step for updating.

**Comment by manato** [comment]
@amc-nu @tokuda99 @urasakikeisuke 
Before merging this PR, would you mind fixing `pre-commit.ci` error since it is required to proceed merging process?

**Comment by amc-nu** [comment]
@manato fixed the remaining issues. Ansible linting is still failing, but the files are unrelated to this PR.

**Comment by manato** [comment]
@amc-nu 
Thanks for your prompt handling!

**Pull request merged**
